import { test, expect,  } from '@playwright/test';

test('test', async ({ page }) => {
  test.setTimeout(130000)
  await page.goto('https://flirb2clab.b2clogin.com/flirb2clab.onmicrosoft.com/b2c_1a_core_signupsignin/oauth2/v2.0/authorize?client_id=49dbbbcc-529a-4e0d-b557-0a7d3232eaae&redirect_uri=https%3A%2F%2Fcustomerqa.flir.com&response_type=code%20id_token&scope=openid%20profile&state=OpenIdConnect.AuthenticationProperties%3DQmF2udLqm9gZK0TIMJoQn2ws8vydzmshDLgZitl0FpYsoGO3cu9IhhRqwqbA5OoAtNAC084yW8JV5XKmbZ9bpbLiyfNWpnI7Gmhe1r4ubfAkK7mNn4eI_L9FV5RE03wteLean2IgKjdt6uqVZ9LWrV5IIV0YkOi2gsIEmTUqR67xmrj-lK_LUwFLEhPGFOs8&response_mode=form_post&nonce=638583068493181771.ZGQ3ODZhY2UtZTA2YS00MWYwLWIzMzMtZDRjMGJmZDg0MTA0N2ExOTllMTktMjFjYi00NzJhLWIxZmYtN2Y2OTAyODg0ODky&x-client-SKU=ID_NET461&x-client-ver=6.8.0.0');
  await page.getByPlaceholder('Email Address').click();
  await page.getByPlaceholder('Email Address').fill('manualqa+tr@futuresight.co');
  await page.getByPlaceholder('Email Address').press('Enter');
  await page.getByPlaceholder('Password').click();
  await page.getByPlaceholder('Password').fill('9xbT9uN#amX!hhvkCCyO');
  await page.getByRole('button', { name: 'Sign in' }).click();
  //await page.goto('https://customerqa.flir.com/Home');
  await page.getByRole('button', { name: 'Accept all' }).click();
  await page.locator('li').filter({ hasText: 'Alfonso Thiele My Profile' }).getByRole('link').hover();
  await page.getByRole('link', { name: 'My Profile', exact: true }).click();
  await page.getByRole('button', { name: 'Change Contact Information' }).click();
  //await page.getByPlaceholder('Street Address', { exact: true }).click();
  //await page.getByPlaceholder('Street Address', { exact: true }).press('');
  await page.getByPlaceholder('Street Address', { exact: true }).fill('Kültür, Becerikli Sk.');
  //await page.getByPlaceholder('Street Address', { exact: true }).press('Kültür, Becerikli Sk.');
  //await page.getByPlaceholder('Street Address 2').click();
  await page.getByPlaceholder('City').click();
  //await page.getByPlaceholder('City').press('Home');
  await page.getByPlaceholder('City').fill('Ankara');
  //await page.getByPlaceholder('City').press('ControlOrMeta+V');
  await page.getByPlaceholder('Postal Code').click();
  //await page.getByPlaceholder('Postal Code').press('Shift+Home');
  await page.getByPlaceholder('Postal Code').fill('64200');
  await page.getByPlaceholder('Phone Number').click();
  //await page.getByPlaceholder('Phone Number').click();
  //await page.getByPlaceholder('Phone Number').press('Shift+Home');
  await page.getByPlaceholder('Phone Number').fill('903124306766');
  //await page.getByPlaceholder('Phone Number').press('ControlOrMeta+V');
  await page.getByPlaceholder('Phone Number').click();
  await page.getByLabel('Continue').click();
  await page.getByRole('link', { name: 'Repair/Service' }).click();
  await page.getByRole('link', { name: 'Repair and Service' }).click();
  await page.getByRole('button', { name: 'CREATE NEW REQUEST' }).click();
  await page.getByRole('button', { name: 'CONTINUE' }).click();
  await page.getByText('Select').nth(2).click();
  await page.locator('label').nth(3).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByPlaceholder('Start searching...').fill('90203-0101');
  await page.getByRole('button', { name: 'SEARCH' }).click();
  await page.locator('rma-select-product-table-row').filter({ hasText: 'FLIR E96 42 DEGPART: 90203-' }).getByRole('button').click();
  await page.getByPlaceholder('Serial number').click();
  //await page.getByPlaceholder('Serial number').press('ControlOrMeta+V');
  await page.getByPlaceholder('Serial number').fill('90208244');
  await page.getByRole('button', { name: 'Add' }).click();
  await page.locator('#serial-input-1').click();
  //await page.locator('#serial-input-1').press('ControlOrMeta+V');
  //await page.locator('#serial-input-1').press('Insert');
  await page.locator('#serial-input-1').fill('90200785');
  await page.getByRole('button', { name: 'Add' }).click();
  await page.getByRole('button', { name: 'YES' }).click();
  await page.getByRole('button', { name: 'SAVE & CONTINUE' }).click();
  
await page.getByLabel('FLIR E96 42 DEG PART: 90203-0101 SERIAL NUMBER: 90208244').getByText('The product is experiencing').click();
await page.getByRole('button', { name: 'Next' }).click();
await page.getByLabel('Description of Issue*').click();
//await page.getByLabel('Description of Issue*').press('CapsLock');
//await page.getByLabel('Description of Issue*').fill('I');
//await page.getByLabel('Description of Issue*').press('CapsLock');
await page.getByLabel('Description of Issue*').fill('item loose and faulty');
await page.getByRole('button', { name: 'Next' }).click();
//await page.getByLabel('FLIR E96 42 DEG PART: 90203-0101 SERIAL NUMBER: 90208244').getByText('Other/Special Request').click();
await page.getByText('No thanks, I only want repair').click();
await page.getByRole('button', { name: 'Next' }).click();
await page.getByRole('button', { name: 'Next' }).click();
await page.getByRole('button', { name: 'Next' }).click();
//await page.getByText('item loose and faulty').click();
//await page.getByRole('button', { name: 'NEXT PRODUCT FORM' }).click();
//await page.getByRole('button', { name: 'product-icon FLIR E96 42 DEG PART: 90203-0101 SERIAL NUMBER: 90208244 ' }).press('Tab');
//await page.getByRole('button', { name: 'BACK' }).click();
//await page.getByRole('button', { name: 'Back' }).click();
//await page.getByText('Product 1:').click();
//await page.locator('rma-draft-progress-indictator').getByText('SAVE & EXIT').click();
//await page.getByRole('link', { name: 'Repair and Service' }).click();
//await page.goto('https://customerqa.flir.com/Return/EndUser/History');
//await page.locator('#ContentPlaceHolder1_DraftRmaRepairList1_RpRepair_LnkSelect_0').click();
//await page.getByText('PRODUCT DETAILS').click();
//await page.getByText('CONTACT + SHIPPING').click();
await page.getByText('CONTACT + SHIPPING').click();
await page.getByText('CHANGE').first().click();
await page.getByRole('button', { name: 'Save' } ).click();
//await page.getByText('ADDITIONAL INFO').click();
//await page.getByText('CONTACT + SHIPPING').click();
//await page.getByText('CHANGE').nth(1).click();
await page.locator('#main').click();
await page.getByRole('button', { name: 'Save & Continue' }).click();
await page.getByLabel('Shipping both to and return').check();
await page.getByRole('button', { name: 'Save & Continue' }).click();
await page.getByRole('button', { name: 'Continue' }).click();
await page.getByRole('button', { name: 'Continue' }).click();
//await page.locator('#referenceSummaryInput').click();
//await page.getByText('Would you like to add a reference? Note A reference or name for you to recall').click();
await page.getByRole('button', { name: 'Continue' }).click();
//await page.getByLabel('Not Military User').check();
await page.getByLabel('Not Military User').check();
await page.getByRole('button', { name: 'Continue' }).click();
await page.getByRole('button', { name: 'Add Non-US export' }).click();
await page.locator('#country').selectOption('223: TR');
//await page.getByRole('textbox').click();
await page.getByRole('textbox').fill('TK test 01');
await page.getByRole('button', { name: 'Continue' }).click();
await page.getByText('Yes').click();
await page.getByRole('button', { name: 'Continue' }).click();
await page.locator('label').filter({ hasText: 'No' }).first().click();
//await page.locator('#mat-dialog-2').press('Escape');
//await page.getByText('Other parties involved Help').click();
await page.locator('#isStorageFacilityN').check();
await page.locator('label').filter({ hasText: 'No' }).nth(2).click();
//await page.locator('#mat-dialog-3').press('Escape');
await page.getByText('YesNo').nth(2).click();
//await page.locator('#mat-dialog-4').press('Escape');
await page.locator('#isFreightForwarderN').check();
await page.locator('#isDistributorN').check();
await page.getByRole('button', { name: 'Continue' }).click();
await page.getByLabel('None').check();
await page.getByRole('button', { name: 'Continue' }).click();
await page.getByText('No', { exact: true }).click();
await page.getByRole('textbox').first().click();
await page.getByRole('textbox').first().fill('security and observation');
await page.getByRole('textbox').nth(1).click();
await page.getByRole('textbox').nth(1).fill('outside in the garden');
await page.getByRole('textbox').nth(1).press('Tab');
await page.getByRole('textbox').nth(2).fill('security and observation');
await page.getByRole('button', { name: 'Continue' }).click();
await page.getByRole('button', { name: 'Continue' }).click();
await page.locator('.col-md-2').click();
await page.getByRole('button', { name: 'Continue' }).click();
await page.getByRole('checkbox').check();
await page.getByRole('button', { name: 'Submit' }).click();
await page.goto('https://customerqa.flir.com/Return/Request/summary-return?v=approval');
//await page.goto('https://flir--tst.custhelp.com/');
//await page.getByPlaceholder('Search...').click();
//await page.getByRole('link', { name: 'Go to My Questions >>' }).click();
//await page.getByRole('button', { name: 'Filter by category' }).click();
//await page.locator('#yui_3_18_1_1_1722714176816_1057').getByRole('cell').nth(3).click();
//await page.goto('https://flir--tst.custhelp.com/');
//await page.getByRole('link', { name: 'Ask a Question' }).click();
//await page.goto('https://flir--tst.custhelp.com/');
});
//#############################################################


