import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://flirb2clab.b2clogin.com/flirb2clab.onmicrosoft.com/b2c_1a_core_signupsignin/oauth2/v2.0/authorize?client_id=49dbbbcc-529a-4e0d-b557-0a7d3232eaae&redirect_uri=https%3A%2F%2Fcustomerqa.flir.com&response_type=code%20id_token&scope=openid%20profile&state=OpenIdConnect.AuthenticationProperties%3DwKbbYxi9nR1tVOzesFavK6Vqv-dXaR2YmI13srQRexXAiLPzR67KM_OZAxKFnZXanmHUgpLteQ734K_DPazNV8yCj5zNrWInZflMhbl1tTZnkPk6K5llyytTuLaGAFCLot6UzXOmpVGoRYAILKTVMwgiBWWsu1dRDeATft1VNyKHovzTf1z8VKqyphISF7CY&response_mode=form_post&nonce=638583203940257107.MzEyZDY4Y2MtNzgxZi00YTZhLTk4NjEtOWY2NTdmZDQ5MWYyMWJjZTBiNWEtNjQwZS00Zjk2LTg3OTUtN2UzNzlhNDI3NDJh&x-client-SKU=ID_NET461&x-client-ver=6.8.0.0');
  await page.getByPlaceholder('Email Address').click();
  await page.getByPlaceholder('Email Address').fill('manualqa+tr@futuresight.co');
  await page.getByLabel('Continue').click();
  await page.getByPlaceholder('Password').click();
  await page.getByPlaceholder('Password').fill('9xbT9uN#amX!hhvkCCyO');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('button', { name: 'Accept all' }).click();
  await page.getByRole('link', { name: 'Repair and Service' }).click();
  await page.getByRole('button', { name: 'CREATE NEW REQUEST' }).click();
  await page.getByRole('button', { name: 'CONTINUE' }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByPlaceholder('Start searching...').fill('90203-0101');
  await page.getByRole('button', { name: 'SEARCH' }).click();
  await page.locator('rma-select-product-table-row').filter({ hasText: 'FLIR E96 42 DEGPART: 90203-' }).getByRole('button').click();
  await page.getByPlaceholder('Serial number').click();
  await page.getByPlaceholder('Serial number').fill('90208244');
  await page.getByRole('button', { name: 'Add' }).click();
  await page.locator('#serial-input-1').click();
  await page.locator('#serial-input-1').press('ControlOrMeta+c');
  await page.locator('#serial-input-1').fill('90200785');
  await page.getByRole('button', { name: 'Add' }).click();
  await page.getByRole('button', { name: 'YES' }).click();
  await page.getByRole('button', { name: 'SAVE & CONTINUE' }).click();
  await page.getByLabel('FLIR E96 42 DEG PART: 90203-0101 SERIAL NUMBER: 90208244').getByText('The product is experiencing').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByLabel('Description of Issue*').click();
  await page.getByLabel('Description of Issue*').press('CapsLock');
  await page.getByLabel('Description of Issue*').fill('N');
  await page.getByLabel('Description of Issue*').press('CapsLock');
  await page.getByLabel('Description of Issue*').fill('Not working ');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByLabel('No thanks, I only want repair').check();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByText('CONTACT + SHIPPING').click();
  await page.getByRole('button', { name: 'Save & Continue' }).click();
  await page.locator('.col-md-8').first().click();
  await page.getByRole('button', { name: 'Save & Continue' }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByLabel('Not Military User').check();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Add Non-US export' }).click();
  await page.locator('#country').selectOption('223: TR');
  await page.getByRole('textbox').click();
  await page.getByRole('textbox').press('CapsLock');
  await page.getByRole('textbox').fill('TK T');
  await page.getByRole('textbox').press('CapsLock');
  await page.getByRole('textbox').fill('TK test 01');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByLabel('Yes').check();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.locator('#isIntegratorN').check();
  await page.locator('#isStorageFacilityN').check();
  await page.locator('#isCustomBrokerN').check();
  await page.locator('#isFreightForwarderN').check();
  await page.locator('#isDistributorN').check();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByLabel('None').check();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByText('Intended Use Help with this').click();
  await page.locator('rma-form-gtc-intent div').filter({ hasText: 'No' }).nth(2).click();
  await page.getByRole('textbox').first().click();
  await page.getByRole('textbox').first().press('CapsLock');
  await page.getByRole('textbox').first().fill('S');
  await page.getByRole('textbox').first().press('CapsLock');
  await page.getByRole('textbox').first().fill('Security');
  await page.getByRole('textbox').nth(1).click();
  await page.getByRole('textbox').nth(1).press('CapsLock');
  await page.getByRole('textbox').nth(1).fill('E');
  await page.getByRole('textbox').nth(1).press('CapsLock');
  await page.getByRole('textbox').nth(1).fill('Enviroment');
  await page.getByRole('textbox').nth(2).click();
  await page.getByRole('textbox').nth(2).press('CapsLock');
  await page.getByRole('textbox').nth(2).fill('S');
  await page.getByRole('textbox').nth(2).press('CapsLock');
  await page.getByRole('textbox').nth(2).fill('Security');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('textbox').nth(2).click();
  await page.getByRole('textbox').nth(2).fill('Security and');
  await page.getByRole('textbox').nth(1).click();
  await page.getByRole('textbox').nth(1).fill('Enviroment and');
  await page.getByRole('textbox').first().click();
  await page.getByRole('textbox').first().fill('Security and');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('textbox').nth(2).click();
  await page.getByRole('textbox').nth(2).fill('Security and undefined');
  await page.getByRole('textbox').nth(2).press('ControlOrMeta+Shift+ArrowLeft');
  await page.getByRole('textbox').nth(2).press('ControlOrMeta+c');
  await page.getByRole('textbox').nth(1).click();
  await page.getByRole('textbox').nth(1).fill('Enviroment and undefined');
  await page.getByRole('textbox').first().click();
  await page.getByRole('textbox').first().fill('Security and undefined');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByText('Declaration I certify that').click();
  await page.getByText('I certify that the').click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.locator('rma-form-summary-part1-consents div').nth(1).click();
  await page.getByText('Order is expressly').click();
  await page.getByText('Order is expressly').click();
  await page.getByRole('checkbox').check();
  await page.getByRole('button', { name: 'Submit' }).click();
});