import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  test.setTimeout(200000)
  await page.goto('https://customerqa.flir.com/'); 
  await page.getByPlaceholder('Email Address').click();
  await page.getByPlaceholder('Email Address').fill('manualqa+tr@futuresight.co');
  await page.getByLabel('Continue').click(); expect (page.locator( '#continue' ).first()).toBeVisible();
  await page.getByPlaceholder('Password').click();
  await page.getByPlaceholder('Password').fill('9xbT9uN#amX!hhvkCCyO'); 
  await page.getByRole('button', { name: 'Sign in' }).click(); 
  await page.getByRole('button', { name: 'Accept all' }).click(); 
  await page.locator('li').filter({ hasText: 'Alfonso Thiele My Profile' }).getByRole('link').hover();
  await page.getByRole('link', { name: 'My Profile', exact: true }).click(); 
  await page.getByRole('button', { name: 'Change Contact Information' }).click(); 
  await page.getByPlaceholder('Street Address', { exact: true }).click(); 
  await page.getByPlaceholder('Street Address', { exact: true }).fill('Kültür, Becerikli Sk.');
  await page.getByLabel('Continue').click(); 
  await page.getByRole('link', { name: 'Repair/Service' }).click(); 
  await page.getByRole('link', { name: 'Repair and Service' }).click(); 
  await page.getByRole('button', { name: 'CREATE NEW REQUEST' }).click(); 
  await page.getByRole('button', { name: 'CONTINUE' }).click(); 
  await page.locator('label').nth(3).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByPlaceholder('Start searching...').fill('90203-0101');
  await page.getByRole('button', { name: 'SEARCH' }).click();
  await page.locator('rma-select-product-table-row').filter({ hasText: 'FLIR E96 42 DEGPART: 90203-' }).getByRole('button').click();
  await page.getByPlaceholder('Serial number').click();
  await page.getByPlaceholder('Serial number').fill('90208244');
  await page.getByRole('button', { name: 'Add' }).click();
  await page.locator('#serial-input-1').click();
  await page.locator('#serial-input-1').fill('90200785');
  await page.getByRole('button', { name: 'Add' }).click();
  await page.getByRole('button', { name: 'YES' }).click();
  await page.getByRole('button', { name: 'SAVE & CONTINUE' }).click();
  await page.getByLabel('FLIR E96 42 DEG PART: 90203-0101 SERIAL NUMBER: 90208244').getByText('The product is experiencing').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByLabel('Description of Issue*').click();
  await page.getByLabel('Description of Issue*').fill('item loose and faulty');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByLabel('No thanks, I only want repair').check();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByText('3', { exact: true }).click();
  await page.getByText('CONTACT + SHIPPING').click();
  await page.getByText('CHANGE').first().click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'Save & Continue' }).click();
  await page.getByText('Shipping both to and return').click();
  await page.getByRole('button', { name: 'Save & Continue' }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.locator('drag-and-drop div').filter({ hasText: 'Uploaded:' }).nth(1).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.locator('#referenceSummaryInput').click();
  await page.getByText('Would you like to add a reference? Note A reference or name for you to recall').click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByLabel('Not Military User').check();  
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Add Non-US export' }).click();
  await page.locator('#country').selectOption('223: TR');
  await page.getByRole('textbox').click();
  await page.getByRole('textbox').fill('TK test 01');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByLabel('Yes').click(); 
  await page.getByRole('button', { name: 'Continue' }).click(); 
  await page.locator('#isIntegratorN').check(); 
  await page.locator('#isStorageFacilityN').check(); 
  await page.locator('#isCustomBrokerN').check(); 
  await page.locator('#isFreightForwarderN').check(); 
  await page.locator('#isDistributorN').check(); 
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByLabel('None').check(); 
  await page.getByRole('button', { name: 'Continue' }).click(); 
  await page.getByText('No', { exact: true }).click();
  await page.getByRole('textbox').first().click(); 
  await page.getByRole('textbox').first().fill('security and observation');
  await page.getByRole('textbox').nth(1).click();
  await page.getByRole('textbox').nth(1).fill('outside in the garden');
  await page.getByRole('textbox').nth(2).click();
  await page.getByRole('textbox').nth(2).fill('security and observation');
  await page.getByRole('button', { name: 'Continue' }).click(); 
  await page.getByRole('button', { name: 'Continue' }).click(); 
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByText('Declaration I certify that').click();
  await page.getByText('I certify that the').click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByText('Order is expressly').click();
  await page.getByText('Order is expressly').click();
  await page.getByRole('checkbox').check();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.goto('https://customerqa.flir.com/Return/Request/summary-return?v=approval'); 
});